/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.5.1/samples
 */
plugins {
    kotlin("js") version "1.7.20"
}

repositories {
    jcenter()
    mavenCentral()
}

kotlin {
    js {
        nodejs {
        }
    }
}